name: pixiv_func_android
description: Pixiv 第三方客户端

publish_to: 'none'
version: 0.10.2

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  json_annotation: ^4.3.0
  get: ^4.3.8
  dio: ^4.0.3
  crypto: ^3.0.1
  intl: ^0.17.0
  logger: ^1.1.0
  shared_preferences: ^2.0.8
  sqflite: ^2.0.0+4
  extended_image: ^5.1.3
  extended_nested_scroll_view: ^5.0.0
  waterfall_flow: ^3.0.1
  pull_to_refresh_notification: ^2.2.0
  loading_more_list: ^4.1.0
  html: ^0.15.0
  permission_handler: ^8.3.0
  image_picker: ^0.8.4+4
dev_dependencies:
  flutter_lints: ^1.0.4
  json_serializable: ^6.0.1
  build_runner: ^2.1.5
flutter:
  uses-material-design: true
  assets:
    - assets/stamps/
    - assets/xiaocao.png
    - assets/kotlin-logo.png
    - assets/dart-logo.png